# Dataset Configuration
train_dataset:
  _target_: fish_speech.datasets.semantic.AutoTextSemanticInstructionIterableDataset
  proto_files:
    - data/protos
  tokenizer: ${tokenizer}
  causal: true
  max_length: ${max_length}
  use_speaker: false
  interactive_prob: 0.7
  metadata_path: "D:/fish_cloner/fish-speech/indic-hindi-english-dataset/metadata_fixed.csv"
  wav_folder: "D:/fish_cloner/fish-speech/indic-hindi-english-dataset/wav/"

val_dataset:
  _target_: fish_speech.datasets.semantic.AutoTextSemanticInstructionIterableDataset
  proto_files:
    - data/protos
  tokenizer: ${tokenizer}
  causal: true
  max_length: ${max_length}
  use_speaker: false
  interactive_prob: 0.7
  metadata_path: "D:/fish_cloner/fish-speech/indic-hindi-english-dataset/metadata_fixed.csv"
  wav_folder: "D:/fish_cloner/fish-speech/indic-hindi-english-dataset/wav/"
